spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB

#mybatis:
#  mapperLocations: classpath:mapping/*.xml
#  typeAliasesPackage: com.cheirmin.thymeleaf.pojo
#
#logging:
#    level:
#        com.cheirmin.dao.AdvertisementMapper: ERROR
server:
  port: 80
  context-path: /exbookstore
#